# Generated by Django 5.1.7 on 2025-04-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin', models.CharField(max_length=100)),
                ('temat', models.CharField(max_length=255)),
                ('plik', models.FileField(blank=True, null=True, upload_to='zajecia_pliki/')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje_nauczyciela', to=settings.AUTH_USER_MODEL)),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje_ucznia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WolnyTermin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('godzina', models.TimeField()),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
