# Generated by Django 5.1.7 on 2025-04-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='numer_telefonu',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
