# Generated by Django 5.1.7 on 2025-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_profil_numer_telefonu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='numer_telefonu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='termin',
            field=models.DateTimeField(),
        ),
    ]
