# Generated by Django 5.1.7 on 2025-04-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_profil_numer_telefonu_alter_rezerwacja_termin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwacja',
            name='data_dodania',
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='plik',
            field=models.FileField(blank=True, null=True, upload_to='rezerwacje/'),
        ),
    ]
