# Generated by Django 5.1.7 on 2025-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_remove_rezerwacja_data_dodania_alter_rezerwacja_plik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Księgowość',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='Panel Księgowości', max_length=100)),
            ],
            options={
                'permissions': [('can_view_ksiegowosc', 'Może przeglądać panel księgowości')],
            },
        ),
    ]
