# Generated by Django 5.1.7 on 2025-04-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_księgowość'),
    ]

    operations = [
        migrations.CreateModel(
            name='UstawieniaPlatnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_za_godzine', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numer_telefonu', models.CharField(max_length=15)),
                ('numer_konta', models.CharField(max_length=32)),
            ],
        ),
    ]
