# Generated by Django 5.1.7 on 2025-04-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_ustawieniaplatnosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustawieniaplatnosci',
            name='wlasciciel_konta',
            field=models.CharField(default='', max_length=100),
        ),
    ]
