# Generated by Django 5.1.7 on 2025-04-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_ustawieniaplatnosci_wlasciciel_konta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ustawieniaplatnosci',
            name='wlasciciel_konta',
        ),
        migrations.AddField(
            model_name='ustawieniaplatnosci',
            name='dane_odbiorcy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ustawieniaplatnosci',
            name='numer_konta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ustawieniaplatnosci',
            name='numer_telefonu',
            field=models.CharField(max_length=20),
        ),
    ]
