# Generated by Django 5.1.7 on 2025-04-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_remove_ustawieniaplatnosci_wlasciciel_konta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustawieniaplatnosci',
            name='wlasciciel_konta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
