# Generated by Django 5.1.7 on 2025-04-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_ustawieniaplatnosci_wlasciciel_konta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ustawieniaplatnosci',
            name='cena_za_godzine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
