# Generated by Django 5.1.7 on 2025-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_ustawieniaplatnosci_cena_za_godzine'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='poziom_nauczania_podstawowy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='poziom_nauczania_rozszerzony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ustawieniaplatnosci',
            name='cena_za_godzine',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
            preserve_default=False,
        ),
    ]
