# Generated by Django 5.1.7 on 2025-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_profil_opis_profil_poziom_nauczania_podstawowy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='poziom_nauczania_podstawowy',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='poziom_nauczania_rozszerzony',
        ),
        migrations.AddField(
            model_name='profil',
            name='poziom_nauczania',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profil',
            name='tytul_naukowy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profil',
            name='numer_telefonu',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='opis',
            field=models.TextField(blank=True, default='Brak opisu'),
            preserve_default=False,
        ),
    ]
