# Generated by Django 5.1.7 on 2025-04-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_remove_profil_is_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='numer_telefonu',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='poziom_nauczania',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='tytul_naukowy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
