# Generated by Django 5.1.7 on 2025-04-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_profil_numer_telefonu_alter_profil_opis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
