# Generated by Django 5.1.7 on 2025-04-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_profil_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='przedmioty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
