# Generated by Django 5.1.7 on 2025-04-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_profil_przedmioty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrzedmiotCennik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('poziom', models.CharField(choices=[('podstawowy', 'Podstawowy'), ('rozszerzony', 'Rozszerzony')], max_length=20)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
