# Generated by Django 5.1.7 on 2025-05-01 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_przedmiotcennik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StawkaNauczyciela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przedmiot', models.CharField(max_length=100)),
                ('poziom', models.CharField(choices=[('podstawowy', 'Podstawowy'), ('rozszerzony', 'Rozszerzony')], max_length=20)),
                ('stawka', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nauczyciel', 'przedmiot', 'poziom')},
            },
        ),
    ]
