# Generated by Django 5.1.7 on 2025-06-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_stawkanauczyciela'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='material_po_zajeciach',
            field=models.FileField(blank=True, null=True, upload_to='materialy/'),
        ),
    ]
