# Generated by Django 5.1.7 on 2025-06-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_rezerwacja_excalidraw_key_onlinestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwacja',
            name='excalidraw_key',
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='excalidraw_room_id',
            field=models.CharField(default='b7ba404134942dbc', max_length=64),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='excalidraw_room_key',
            field=models.CharField(default='6885bee39e93e1a23d43977b2f746d0299eb0aa7ffda2591fe342d93a3f044f5', max_length=128),
        ),
    ]
