# Generated by Django 5.1.7 on 2025-06-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_remove_rezerwacja_excalidraw_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='excalidraw_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='excalidraw_room_id',
            field=models.CharField(default='c669e0dee5f6b46e', max_length=64),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='excalidraw_room_key',
            field=models.CharField(default='4b800568cfb35d12d49fe3a113faf108a74b92b8760c6071fbd32532095489a1', max_length=128),
        ),
    ]
