# Generated by Django 5.1.7 on 2025-08-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_rezerwacja_excalidraw_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='excalidraw_room_id',
            field=models.CharField(default='3158685b35dd9d77', max_length=64),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='excalidraw_room_key',
            field=models.CharField(default='0de8759014379bea4577217dd825a97a5c02c4ae5c2df4909cbd6d52145cbb86', max_length=128),
        ),
    ]
