# Generated by Django 5.1.7 on 2025-08-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_alter_rezerwacja_excalidraw_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='excalidraw_room_id',
            field=models.CharField(default='26a409c03a412386', max_length=64),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='excalidraw_room_key',
            field=models.CharField(default='a1f033ca08f56f5ae3e934b8e54134a342843fa7f9b8f316aa921a3f9929741e', max_length=128),
        ),
    ]
