# Generated by Django 5.1.7 on 2025-10-02 04:59

import panel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_alter_rezerwacja_excalidraw_room_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'ordering': ['termin']},
        ),
        migrations.AlterModelOptions(
            name='wolnytermin',
            options={'ordering': ['data', 'godzina']},
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='excalidraw_room_id',
            field=models.CharField(default=panel.models.default_excalidraw_room_id, max_length=64),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='excalidraw_room_key',
            field=models.CharField(default=panel.models.default_excalidraw_room_key, max_length=128),
        ),
        migrations.AddIndex(
            model_name='rezerwacja',
            index=models.Index(fields=['termin'], name='panel_rezer_termin_97fd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='rezerwacja',
            index=models.Index(fields=['nauczyciel', 'termin'], name='panel_rezer_nauczyc_7b840b_idx'),
        ),
        migrations.AddIndex(
            model_name='rezerwacja',
            index=models.Index(fields=['uczen', 'termin'], name='panel_rezer_uczen_i_d8f806_idx'),
        ),
        migrations.AddIndex(
            model_name='wolnytermin',
            index=models.Index(fields=['data', 'godzina'], name='panel_wolny_data_ccec44_idx'),
        ),
        migrations.AddIndex(
            model_name='wolnytermin',
            index=models.Index(fields=['nauczyciel', 'data', 'godzina'], name='panel_wolny_nauczyc_f087d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='rezerwacja',
            constraint=models.UniqueConstraint(fields=('nauczyciel', 'termin'), name='uniq_rez_teacher_datetime'),
        ),
        migrations.AddConstraint(
            model_name='wolnytermin',
            constraint=models.UniqueConstraint(fields=('nauczyciel', 'data', 'godzina'), name='uniq_slot_teacher_date_time'),
        ),
    ]
