# Generated by Django 5.1.7 on 2025-10-07 04:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0025_alter_rezerwacja_options_alter_wolnytermin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='przedmiotcennik',
            options={'verbose_name': 'Przedmiot w cenniku', 'verbose_name_plural': 'Cennik przedmiotów'},
        ),
        migrations.AddField(
            model_name='przedmiotcennik',
            name='cena_uczen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Cena dla ucznia [zł/h]'),
        ),
        migrations.AlterField(
            model_name='przedmiotcennik',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Cena nauczyciela [zł/h]'),
        ),
        migrations.AlterUniqueTogether(
            name='przedmiotcennik',
            unique_together={('nazwa', 'poziom')},
        ),
    ]
