# Generated by Django 5.1.7 on 2025-10-08 05:19

import django.core.validators
import django.db.models.deletion
import panel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_alter_przedmiotcennik_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='accessibility_notes',
            field=models.TextField(blank=True, verbose_name='Uwagi o potrzebach edukacyjnych'),
        ),
        migrations.AddField(
            model_name='profil',
            name='address_line',
            field=models.CharField(blank=True, max_length=160, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=panel.models.avatar_upload_path, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='profil',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AddField(
            model_name='profil',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='profil',
            name='extra_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Drugi numer telefonu'),
        ),
        migrations.AddField(
            model_name='profil',
            name='gdpr_edu_consent',
            field=models.BooleanField(default=False, verbose_name='Zgoda na przetwarzanie danych edukacyjnych'),
        ),
        migrations.AddField(
            model_name='profil',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail opiekuna'),
        ),
        migrations.AddField(
            model_name='profil',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Imię i nazwisko opiekuna'),
        ),
        migrations.AddField(
            model_name='profil',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telefon opiekuna'),
        ),
        migrations.AddField(
            model_name='profil',
            name='marketing_email',
            field=models.BooleanField(default=False, verbose_name='Zgoda na kontakt e-mail'),
        ),
        migrations.AddField(
            model_name='profil',
            name='marketing_sms',
            field=models.BooleanField(default=False, verbose_name='Zgoda na kontakt SMS'),
        ),
        migrations.AddField(
            model_name='profil',
            name='recording_consent',
            field=models.BooleanField(default=False, verbose_name='Zgoda na nagrywanie lekcji'),
        ),
        migrations.AddField(
            model_name='profil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='numer_telefonu',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{6,}$', 'Podaj poprawny numer telefonu.')]),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('action', models.CharField(max_length=120)),
                ('obj_type', models.CharField(blank=True, max_length=80)),
                ('obj_id', models.CharField(blank=True, max_length=80)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
