# Generated by Django 5.1.7 on 2025-10-09 05:04

import django.db.models.deletion
import panel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_profil_accessibility_notes_profil_address_line_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='autopay', max_length=32)),
                ('provider_payment_id', models.CharField(max_length=128, unique=True)),
                ('amount_grosz', models.PositiveIntegerField()),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='panel.rezerwacja')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('issue_date', models.DateField()),
                ('place', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('rate_grosz', models.PositiveIntegerField()),
                ('total_grosz', models.PositiveIntegerField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to=panel.models.invoice_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='panel.rezerwacja')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='panel.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
