# Generated by Django 5.1.7 on 2025-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='poziom_nauki',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='typ_osoby',
            field=models.CharField(blank=True, choices=[('podstawowa', 'Uczeń szkoły podstawowej'), ('srednia', 'Uczeń szkoły średniej'), ('student', 'Student uczelni wyższej')], max_length=15, null=True),
        ),
    ]
