# Generated by Django 5.1.7 on 2025-10-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_rezerwacja_poziom_nauki_rezerwacja_typ_osoby'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='poziom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='przedmiot',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
