# Generated by Django 5.1.7 on 2025-10-17 03:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0030_rezerwacja_poziom_rezerwacja_przedmiot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ustawieniaplatnosci',
            name='cena_za_godzine',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ustawieniaplatnosci',
            name='dane_odbiorcy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ustawieniaplatnosci',
            name='numer_konta',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ustawieniaplatnosci',
            name='numer_telefonu',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='ustawieniaplatnosci',
            name='wlasciciel_konta',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
