# Generated by Django 5.1.7 on 2025-10-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_alter_ustawieniaplatnosci_cena_za_godzine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacja',
            name='odrzucona',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='oplacona',
            field=models.BooleanField(default=False),
        ),
    ]
