# Generated by Django 5.1.7 on 2025-10-18 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0033_paymentconfirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLegalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_owner', models.CharField(default='Bogdan Auguściński', max_length=255)),
                ('site_address', models.CharField(default='Polska (miasto)', max_length=255)),
                ('site_email', models.EmailField(default='polubiszto.pl@gmail.com', max_length=254)),
                ('site_url', models.CharField(default='https://polubiszto.pl', max_length=255)),
                ('payment_operator', models.CharField(default='Autopay oraz płatności BLIK/przelew', max_length=255)),
                ('processors', models.CharField(default='hosting Render/OVH, poczta, Autopay, narzędzia analityczne bez profilowania', max_length=500)),
                ('cookies_desc', models.CharField(default='techniczne (sesja), analityczne zagregowane, preferencje interfejsu', max_length=500)),
                ('video_tools', models.CharField(default='Jitsi (audio/wideo), Excalidraw (tablica współdzielona)', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konfiguracja dokumentów prawnych',
                'verbose_name_plural': 'Konfiguracje dokumentów prawnych',
            },
        ),
    ]
