# Generated by Django 5.1.7 on 2025-10-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0034_sitelegalconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='recording_consent',
        ),
    ]
